#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use FosterCommerce\Groot\Console\BuildCommand;
use FosterCommerce\Groot\Console\NewCommand;

require_once __DIR__ . '/bootstrap.php';

$app = new Application('Groot');

$app->add(new BuildCommand);
$app->add(new NewCommand);

$app->run();
